version: "3"
services:
  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # volumes:
    #   - ./backend:/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./backend/.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  frontend:
    build: ./frontend
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3000:80"
    # env_file:
    #   - ./frontend/.env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:


